### ISSUE TITLE
utmgeo() routine needs correction

### ISSUE THREAD

**Issue by danielpeter** [mherman09/Hdef#6]
Please note that your utmgeo() routine provided to convert long/lat to UTM coordinates contains two 2 mistakes:

source file: Hdef/src/map_module.f90

line 147:
https://github.com/mherman09/Hdef/blob/d830e36f879684f60171ffca35be5009f94cc070/src/map_module.f90#L147

wrong: `f3 = 15.d0*e4/256.d0*45.d0*e6/1024.d0`
correct would be: `f3 = 15.d0*e4/256.d0 + 45.d0*e6/1024.d0`

line 209:
https://github.com/mherman09/Hdef/blob/d830e36f879684f60171ffca35be5009f94cc070/src/map_module.f90#L209

wrong:  `f3 = 5.d0*3.d0*t1 + 10.d0*c1 - 4.d0*c1**2 - 9.d0*ep2`
correct would be:  `f3 = 5.d0 + 3.d0*t1 + 10.d0*c1 - 4.d0*c1**2 - 9.d0*ep2`

the above corrections could be verified by looking at the original publication:
Snyder, J.P., Map projections - a working manual, USGS professional paper 1395, 1987
https://doi.org/10.3133/pp1395

line 147 mistake/correction: see page 61, eq. 3-21 for M
line 209 mistake/correction: see page 63, eq. 8-17 for phi

the above error will lead to a positional error of ~7 m when converting lon/lat to UTM.

best regards,
daniel

**Comment by mherman09** [comment]
Great catch - thanks! I have not used this subroutine in years (I mostly use GDAL tools for these sorts of things now), so it has not been carefully checked or tested. I will make the update soon.
